version: "3"

services:
  buncker-game-server:
    container_name: "bunker-game"
    build:
      context: ./bunkergame
      dockerfile: Dockerfile
    command: bash -c " make migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    env_file:
      - bunkergame/.env
    volumes:
      - ./bunkergame/:/bunkergame/
    ports:
      - 8000:8000
