# Generated by Django 5.2 on 2025-04-28 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameEngine',
            fields=[
                ('_game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_map_descriptions', models.IntegerField(null=True)),
                ('_bunker_descritions', models.IntegerField(null=True)),
                ('_user_count', models.IntegerField(null=True)),
                ('_turn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('profession', models.IntegerField()),
                ('health', models.IntegerField()),
                ('bio_character', models.IntegerField()),
                ('additional_skills', models.IntegerField()),
                ('hobby', models.IntegerField()),
                ('spec_condition', models.IntegerField()),
                ('items', models.IntegerField()),
                ('is_in_game', models.BooleanField(default=False)),
                ('vote_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('game_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gameengine.gameengine')),
            ],
        ),
    ]
