# Generated by Django 5.2 on 2025-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameengine',
            name='game_status',
            field=models.IntegerField(choices=[(0, 'Not Created'), (1, 'Created'), (2, 'In Progress'), (3, 'Turning'), (4, 'Voting'), (5, 'End')], default=0),
        ),
    ]
