# Generated by Django 5.2 on 2025-04-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0002_gameengine_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameengine.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameengine.gameengine'),
        ),
    ]
