# Generated by Django 5.2 on 2025-04-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0005_gameengine_created_at_gameengine_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameengine',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameengine.user'),
        ),
    ]
