# Generated by Django 5.2 on 2025-04-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0008_rename_user_gameuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameengine',
            old_name='_bunker_descritions',
            new_name='bunker_descritions',
        ),
        migrations.RenameField(
            model_name='gameengine',
            old_name='_game_id',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='gameengine',
            old_name='_map_descriptions',
            new_name='map_descriptions',
        ),
        migrations.RenameField(
            model_name='gameengine',
            old_name='_turn',
            new_name='turn',
        ),
        migrations.RenameField(
            model_name='gameengine',
            old_name='_user_count',
            new_name='user_count',
        ),
    ]
