# Generated by Django 5.2 on 2025-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0009_rename__bunker_descritions_gameengine_bunker_descritions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameengine',
            name='game_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
