# Generated by Django 5.2 on 2025-04-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0010_gameengine_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='game_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='game_number',
            field=models.IntegerField(default=0),
        ),
    ]
