# Generated by Django 5.2 on 2025-04-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0011_gameuser_game_name_gameuser_game_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='is_additional_skills_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='is_bio_character_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='is_health_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='is_hobby_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='is_items_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='is_profession_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='is_spec_condition_visible',
            field=models.BooleanField(default=False),
        ),
    ]
