# Generated by Django 5.2 on 2025-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0012_gameuser_is_additional_skills_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameengine',
            name='user_number_turn',
            field=models.IntegerField(default=0),
        ),
    ]
