# Generated by Django 5.2 on 2025-05-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0013_gameengine_user_number_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='vote_id',
            field=models.UUIDField(null=True),
        ),
    ]
