# Generated by Django 5.2 on 2025-05-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0014_alter_gameuser_vote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='is_in_game',
            field=models.BooleanField(default=True),
        ),
    ]
