# Generated by Django 5.2 on 2025-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0015_alter_gameuser_is_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='age',
            field=models.IntegerField(default=-1),
        ),
    ]
