# Generated by Django 5.2 on 2025-05-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0016_gameuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameengine',
            name='ending',
            field=models.CharField(default='', max_length=50),
        ),
    ]
