# Generated by Django 5.2 on 2025-05-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0017_gameengine_ending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameengine',
            name='ending',
            field=models.CharField(default='Конец пока неизвестен', max_length=50),
        ),
    ]
