# Generated by Django 5.2 on 2025-05-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0018_alter_gameengine_ending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='game_name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
