# Generated by Django 5.2 on 2025-05-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameengine', '0019_alter_gameuser_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='is_showed_stat_at_turn',
            field=models.BooleanField(default=False),
        ),
    ]
